デバッグ

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -26,6 +26,12 @@ jobs:
           west zephyr-export
           pip install -r ../zephyr/scripts/requirements-base.txt
 
+      - name: 🔍Debug Show nanopb module.yml
+        run: |
+          echo "===== module.yml from runner ====="
+          cat modules/lib/nanopb/zephyr/module.yml || echo "module.yml not found"
+          echo "==================================="
+
       - name: Build firmware
         run: |
           ls ../zmk/app
