なんでここ？

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -33,12 +33,10 @@ jobs:
         run: |
           echo "===== pwd ====="
           pwd
-          echo "===== ls -R modules/lib/nanopb ====="
-          ls -R modules/lib/nanopb || echo "modules/lib/nanopb not found"
           echo "===== module.yml ====="
-          cat modules/lib/nanopb/zephyr/module.yml || echo "module.yml not found"
+          cat ../modules/lib/nanopb/zephyr/module.yml || echo "module.yml not found"
           echo "===== HEAD ====="
-          cd modules/lib/nanopb || exit 1
+          cd ../modules/lib/nanopb || exit 1
           git log -1 || echo "no log"
 
       - name: Build firmware
